ia64: Make expand_upwards() available again
"mm/vma: move stack expansion logic to mm/vma.c" (commit a9d1f3f2d7fecbc465bd4b16343a2ff8499cc558)
didn't anticipate that ia64 also needs this when putting a guard around
the function prototype for it in mm/vma.h. This broke the build for ia64:

```
mm/mmap.c: In function 'vma_expand_up':
mm/mmap.c:1033:16: error: implicit declaration of function 'expand_upwards'; did you mean 'expand_downwards'? [-Wimplicit-function-declaration]
 1033 |         return expand_upwards(vma, addr);
      |                ^~~~~~~~~~~~~~
      |                expand_downwards
```

...and is fixed now.