Revert "sysctl: Removed unused variable"
ia64 still uses this, so we keep that.

Otherwise we get:
```
kernel/sysctl.c:1504:36: error: 'unaligned_dump_stack' undeclared here (not in a function); did you mean 'trace_dump_stack'?
 1504 |                 .data           = &unaligned_dump_stack,
      |                                    ^~~~~~~~~~~~~~~~~~~~
      |                                    trace_dump_stack
```
...during build.

This reverts commit 39dac316f09ae5a0930878d2cae8aea113648b5a.