Revert "workqueue: Remove unused work_on_cpu_safe"
ia64 is still using this in `arch/ia64/kernel/salinfo.c`, so we keep that.

Otherwise we get:

```
arch/ia64/kernel/salinfo.c: In function 'salinfo_log_new_read':
arch/ia64/kernel/salinfo.c:427:17: error: implicit declaration of function 'work_on_cpu_safe'; did you mean 'work_on_cpu_key'? [-Wimplicit-function-declaration]
  427 |                 work_on_cpu_safe(cpu, salinfo_log_read_cpu, data);
      |                 ^~~~~~~~~~~~~~~~
      |                 work_on_cpu_key
```

...during build.

This reverts commit fc2898ea793a48bc4b74b61cde2d8656f20efdf4.