ia64: replay "mm: introduce memdesc_flags_t"
...otherwise we get these:
```
  CC      arch/ia64/kernel/sys_ia64.o
In file included from ./include/linux/kernel.h:23,
                 from arch/ia64/mm/init.c:8:
arch/ia64/mm/init.c: In function '__ia64_sync_icache_dcache':
arch/ia64/mm/init.c:58:33: error: passing argument 2 of 'const_test_bit' from incompatible pointer type [-Wincompatible-pointer-types]
   58 |         if (test_bit(PG_arch_1, &folio->flags))
      |                                 ^~~~~~~~~~~~~
      |                                 |
      |                                 memdesc_flags_t *
./include/linux/bitops.h:47:24: note: in definition of macro 'bitop'
   47 |          const##op(nr, addr) : op(nr, addr))
      |                        ^~~~
arch/ia64/mm/init.c:58:13: note: in expansion of macro 'test_bit'
   58 |         if (test_bit(PG_arch_1, &folio->flags))
      |             ^~~~~~~~
In file included from ./include/linux/bitops.h:28:
./include/asm-generic/bitops/generic-non-atomic.h:166:64: note: expected 'const volatile long unsigned int *' but argument is of type 'memdesc_flags_t *'
  166 | const_test_bit(unsigned long nr, const volatile unsigned long *addr)
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
arch/ia64/mm/init.c:58:33: error: passing argument 2 of 'generic_test_bit' from incompatible pointer type [-Wincompatible-pointer-types]
   58 |         if (test_bit(PG_arch_1, &folio->flags))
      |                                 ^~~~~~~~~~~~~
      |                                 |
      |                                 memdesc_flags_t *
./include/linux/bitops.h:47:39: note: in definition of macro 'bitop'
   47 |          const##op(nr, addr) : op(nr, addr))
      |                                       ^~~~
arch/ia64/mm/init.c:58:13: note: in expansion of macro 'test_bit'
   58 |         if (test_bit(PG_arch_1, &folio->flags))
      |             ^~~~~~~~
./include/asm-generic/bitops/generic-non-atomic.h:121:66: note: expected 'const volatile long unsigned int *' but argument is of type 'memdesc_flags_t *'
  121 | generic_test_bit(unsigned long nr, const volatile unsigned long *addr)
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
make[6]: *** [scripts/Makefile.build:287: arch/ia64/mm/init.o] Error 1
make[5]: *** [scripts/Makefile.build:556: arch/ia64/mm] Error 2
make[5]: *** Waiting for unfinished jobs....
```

See 53fbef56e07df822ea3029109ffca25328c2e5ac.

Signed-off-by: Johnny Mnemonic <jm@machine-hall.org>