Revert "dma-mapping: remove unused map_page callback"
The ia64 arch code wasn't yet converted to use physical addresses, making
this a build regression:
```
arch/ia64/hp/common/sba_iommu.c:2074:10: error: 'const struct dma_map_ops' has no member named 'map_page'
 2074 |         .map_page               = sba_map_page,
      |          ^~~~~~~~
arch/ia64/hp/common/sba_iommu.c:2074:35: error: initialization of 'struct page * (*)(struct device *, size_t,  dma_addr_t *, enum dma_data_direction,  gfp_t)' {aka 'struct page * (*)(struct device *, long unsigned int,  long long unsigned int *, enum dma_data_direction,  unsigned int)'} from incompatible pointer type 'dma_addr_t (*)(struct device *, struct page *, long unsigned int,  size_t,  enum dma_data_direction,  long unsigned int)' {aka 'long long unsigned int (*)(struct device *, struct page *, long unsigned int,  long unsigned int,  enum dma_data_direction,  long unsigned int)'} [-Wincompatible-pointer-types]
 2074 |         .map_page               = sba_map_page,
      |                                   ^~~~~~~~~~~~
arch/ia64/hp/common/sba_iommu.c:2074:35: note: (near initialization for 'sba_dma_ops.alloc_pages_op')
arch/ia64/hp/common/sba_iommu.c:2075:10: error: 'const struct dma_map_ops' has no member named 'unmap_page'; did you mean 'unmap_phys'?
 2075 |         .unmap_page             = sba_unmap_page,
      |          ^~~~~~~~~~
      |          unmap_phys
arch/ia64/hp/common/sba_iommu.c:2075:35: error: initialization of 'void (*)(struct device *, size_t,  struct page *, dma_addr_t,  enum dma_data_direction)' {aka 'void (*)(struct device *, long unsigned int,  struct page *, long long unsigned int,  enum dma_data_direction)'} from incompatible pointer type 'void (*)(struct device *, dma_addr_t,  size_t,  enum dma_data_direction,  long unsigned int)' {aka 'void (*)(struct device *, long long unsigned int,  long unsigned int,  enum dma_data_direction,  long unsigned int)'} [-Wincompatible-pointer-types]
 2075 |         .unmap_page             = sba_unmap_page,
      |                                   ^~~~~~~~~~~~~~
arch/ia64/hp/common/sba_iommu.c:2075:35: note: (near initialization for 'sba_dma_ops.free_pages')
make[5]: *** [scripts/Makefile.build:287: arch/ia64/hp/common/sba_iommu.o] Error 1
make[4]: *** [scripts/Makefile.build:556: arch/ia64/hp/common] Error 2
```
So let's revert that until a better solution can be found.

This reverts commit 131971f67e258170c678fe572fda95f8cef88e66.